version: '3.7'
 
volumes:
  postgres_data:
  static_volume:

 
services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
   # env_file:
   #   - ./.env
    enviroment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      
  web:
    image: gloom13/yamdb_final:v.3
    restart: always
    volumes:
      - static_volume:/code/static
    expose:
      - "8000"
    depends_on:
      - db
   # env_file:
   #   - ./.env
    enviroment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - static_volume:/code/static
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "1337:80"
    depends_on:
      - web
