# Generated by Django 3.1.2 on 2020-10-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_auto_20201005_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='VVETYS0D1M', max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=255, unique=True, verbose_name='Почта'), max_length=30, unique=True, verbose_name='Псевдоним'),
        ),
    ]
