# Generated by Django 3.1.2 on 2020-10-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_auto_20201005_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='R143RZJBVV', max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
