# Generated by Django 3.1.2 on 2020-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_auto_20201006_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='Y1EKWA4CDJ', max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
