# Generated by Django 3.1.2 on 2020-10-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0009_auto_20201006_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='L2LJA1JMCY', max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
