# Generated by Django 3.1.2 on 2020-10-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0010_auto_20201009_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True, verbose_name='Информация о себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='Z16OEHP26S', max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
