# Generated by Django 3.1.2 on 2020-10-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0011_auto_20201009_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
