# Generated by Django 3.1.2 on 2021-02-13 15:00

import api_v1.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0015_auto_20201013_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2021, validators=[api_v1.utils.max_value_current_year], verbose_name='Год выхода'),
        ),
    ]
